#! /usr/bin/perl

# feather_border - adds a feathered border to an image

use warnings;
use strict;

use lib qw<lib>;

use Gimp::Batch qw<:all>;


my $borderer = Gimp::Batch->new(script_fu_fuzzy_border => image, drawable,
    \'#FAF5C0', 8, TRUE, 1, FALSE, 100, FALSE, TRUE);

my ($in_file, $out_file) = @ARGV;
$borderer->apply($in_file, $out_file);
